DATA PREPARATION

In [24]:
import pandas as pd

df = pd.read_excel("Raisin_Dataset.xlsx")
df.sample(5)

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter,Class
833,78921,376.987817,268.832612,0.701055,82584,0.719924,1144.959,Besni
299,36113,257.641853,181.157079,0.711056,37442,0.694481,737.637,Kecimen
794,105053,490.409597,277.084224,0.825087,107939,0.670404,1297.279,Besni
168,92735,436.985567,271.578785,0.783428,94693,0.704122,1183.447,Kecimen
841,92472,424.419993,282.211505,0.746902,95982,0.746163,1204.610,Besni

MODEL EVALUATION: TRAIN TEST SPLIT

In [25]:
X = df[['Area', 'MajorAxisLength','MinorAxisLength', 'Eccentricity','ConvexArea','Extent','Perimeter']]
y= df['Class']
X.head(3)

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter
0,87524,442.246011,253.291155,0.819738,90546,0.758651,1184.040
1,75166,406.690687,243.032436,0.801805,78789,0.684130,1121.786
2,90856,442.267048,266.328318,0.798354,93717,0.637613,1208.575

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 23)

MODEL TRAINING USING SVM: RBF KERNEL :NOT SCALED

In [27]:
from sklearn.svm import SVC

model = SVC(kernel = "rbf")
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)
print(report)

model.n_iter_

              precision    recall  f1-score   support

       Besni       0.81      0.69      0.75        83
     Kecimen       0.76      0.87      0.81        97

    accuracy                           0.78       180
   macro avg       0.79      0.78      0.78       180
weighted avg       0.79      0.78      0.78       180

array([230], dtype=int32)

MODEL TRAINING USING SVM: LINEAR KERNEL :NOT SCALED

In [ ]:
from sklearn.svm import SVC

model = SVC(kernel = "linear")
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)
print(report)

model.n_iter_

MODEL TRAINING USING SVM: POLY KERNEL :NOT SCALED

In [8]:
from sklearn.svm import SVC

model = SVC(kernel = "poly")
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)
print(report)

model.n_iter_

              precision    recall  f1-score   support

       Besni       0.87      0.66      0.75        83
     Kecimen       0.76      0.92      0.83        97

    accuracy                           0.80       180
   macro avg       0.82      0.79      0.79       180
weighted avg       0.81      0.80      0.80       180

array([299], dtype=int32)

MODEL TRAINING USING SVM: SIGMOID KERNEL :NOT SCALED

In [9]:
from sklearn.svm import SVC

model = SVC(kernel = "sigmoid")
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)
print(report)

model.n_iter_

              precision    recall  f1-score   support

       Besni       0.25      0.31      0.28        83
     Kecimen       0.27      0.22      0.24        97

    accuracy                           0.26       180
   macro avg       0.26      0.26      0.26       180
weighted avg       0.26      0.26      0.26       180

array([420], dtype=int32)

The different kernels selected drastically varied the models' performance. Choosing the best kernel type is important, and we also need to watch the number of iterations. In the above scenario, the linear type performed way too many iterations than the other kernels but with better performance. 
We can use a Data preprocessing technique called scaling to tackle this issue.

SCALING

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [14]:
X_train_scaled

array([[ 2.93259592,  2.18738993,  2.50657197, ...,  2.89731685,
         0.33142573,  2.41945867],
       [-0.41469847, -0.26313549, -0.45771571, ..., -0.36651101,
        -1.0675081 , -0.23400872],
       [-0.2768601 , -0.04924111, -0.30060517, ..., -0.24200993,
        -0.84635927, -0.12564   ],
       ...,
       [ 0.19088734, -0.29176209,  1.0565373 , ...,  0.16693182,
         1.00182539,  0.12968489],
       [ 0.49455248,  0.91334858,  0.08464636, ...,  0.51574591,
         0.56163645,  0.69005833],
       [-0.18786674,  0.4322991 , -0.73911434, ..., -0.14806352,
         0.28941022,  0.19442981]])

MODEL TRAINING USING SVM: RBF KERNEL : SCALED

In [20]:
from sklearn.svm import SVC

model = SVC(kernel = "rbf")
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)
print(report)

model.n_iter_

              precision    recall  f1-score   support

       Besni       0.92      0.78      0.84        83
     Kecimen       0.83      0.94      0.88        97

    accuracy                           0.87       180
   macro avg       0.88      0.86      0.86       180
weighted avg       0.87      0.87      0.87       180

array([308], dtype=int32)

MODEL TRAINING USING SVM: Linear KERNEL : SCALED

In [21]:
from sklearn.svm import SVC

model = SVC(kernel = "linear")
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)
print(report)

model.n_iter_

              precision    recall  f1-score   support

       Besni       0.92      0.78      0.84        83
     Kecimen       0.83      0.94      0.88        97

    accuracy                           0.87       180
   macro avg       0.88      0.86      0.86       180
weighted avg       0.87      0.87      0.87       180

array([2282], dtype=int32)

MODEL TRAINING USING SVM: POLY KERNEL : SCALED

In [22]:
from sklearn.svm import SVC

model = SVC(kernel = "poly")
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)
print(report)

model.n_iter_

              precision    recall  f1-score   support

       Besni       0.78      0.81      0.79        83
     Kecimen       0.83      0.80      0.82        97

    accuracy                           0.81       180
   macro avg       0.80      0.81      0.80       180
weighted avg       0.81      0.81      0.81       180

array([427], dtype=int32)

MODEL TRAINING USING SVM: SIGMOID KERNEL : SCALED

In [23]:
from sklearn.svm import SVC

model = SVC(kernel = "sigmoid")
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)
print(report)

model.n_iter_

              precision    recall  f1-score   support

       Besni       0.75      0.72      0.74        83
     Kecimen       0.77      0.79      0.78        97

    accuracy                           0.76       180
   macro avg       0.76      0.76      0.76       180
weighted avg       0.76      0.76      0.76       180

array([161], dtype=int32)

As we can see, the number of iterations decreased from millions to thousands after using scaled data. Even the performance of the sigmoid kernel improved.